import { Providers } from "src/components/Providers/providers";
import "../styles/settings.css";

export const metadata = {
  title: "FlashCards - Learn faster than you can",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { readonly children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
