import { BackgroundGame } from "src/views/game/components/BackgroundGame/BackgroundGame";
import { Navigation } from "src/components/Navigation/Navigation";

export const metadata = {
  title: "FlashCards - Learn faster than you can",
  description: "Generated by Next.js",
};

export default function GameLayout({ children }: { readonly children: React.ReactNode }) {
  return (
    <BackgroundGame>
      <Navigation />
      <div>{children}</div>
    </BackgroundGame>
  );
}
