import { BackgroundGame } from "src/views/board/components/BackgroundBoard/BackgroundGame";
import { Navigation } from "src/components/Navigation/Navigation";

export const metadata = {
  title: "FlashCards - Learn faster than you can",
  description: "Generated by Next.js",
};

export default function GameLayout({ children }: { readonly children: React.ReactNode }) {
  return (
    <>
      <Navigation />
      {children}
    </>
  );
}
