# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 5343:5342
